# Generated by Django 6.0.3 on 2026-05-11 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_employeeinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinfo',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='accounts.userinfo'),
        ),
    ]
