# Generated by Django 6.0.3 on 2026-05-11 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_employeeinfo_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeinfo',
            old_name='company_name',
            new_name='company',
        ),
    ]
