# Generated by Django 6.0.3 on 2026-05-12 12:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_company_name_employeeinfo_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadid', models.CharField(blank=True, max_length=50, unique=True)),
                ('lead_name', models.CharField(blank=True, max_length=50)),
                ('lead_phone', models.CharField(blank=True, max_length=15)),
                ('lead_email', models.EmailField(blank=True, max_length=254)),
                ('lead_source', models.CharField(blank=True)),
                ('for_type', models.CharField(blank=True)),
                ('status', models.CharField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead', to='accounts.userinfo')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userinfo')),
                ('from_assign_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assign', to='accounts.employeeinfo')),
                ('to_assign_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assigned', to='accounts.employeeinfo')),
            ],
        ),
    ]
