# Generated by Django 6.0.3 on 2026-05-12 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_leads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='company_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='leads',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='for_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='leads',
            name='from_assign_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assign', to='accounts.employeeinfo'),
        ),
        migrations.AlterField(
            model_name='leads',
            name='lead_source',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='leads',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='leads',
            name='to_assign_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned', to='accounts.employeeinfo'),
        ),
    ]
