# Generated by Django 6.0.3 on 2026-05-12 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_leads_company_name_alter_leads_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leads',
            old_name='company_id',
            new_name='company',
        ),
    ]
