# Generated by Django 6.0.3 on 2026-05-15 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_company_id_leads_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('For_type_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('For_type_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_name', to='accounts.leads')),
            ],
        ),
        migrations.CreateModel(
            name='Leadsource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('lead_source_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_source_name', to='accounts.leads')),
            ],
        ),
    ]
