# Generated by Django 6.0.3 on 2026-05-15 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_fortype_leadsource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fortype',
            name='For_type_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='leads',
            name='for_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.fortype'),
        ),
        migrations.AlterField(
            model_name='leads',
            name='lead_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.leadsource'),
        ),
        migrations.AlterField(
            model_name='leadsource',
            name='lead_source_name',
            field=models.CharField(max_length=50),
        ),
    ]
