# Generated by Django 6.0.3 on 2026-05-15 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_fortype_for_type_name_alter_leads_for_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fortype',
            old_name='For_type_name',
            new_name='for_type_name',
        ),
        migrations.RenameField(
            model_name='fortype',
            old_name='For_type_status',
            new_name='for_type_status',
        ),
    ]
