# Generated by Django 6.0.3 on 2026-05-16 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_for_type_name_fortype_for_type_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('project_name', models.CharField(blank=True, max_length=50)),
                ('project_description', models.TextField(blank=True)),
                ('client_name', models.CharField(blank=True, max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('status', models.CharField(choices=[('not started', 'Not Started'), ('in progress', 'In progress'), ('on hold', 'On Hold'), ('completed', 'Completed')], default='not started', max_length=20)),
                ('assign_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to', to='accounts.employeeinfo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='accounts.userinfo')),
            ],
        ),
    ]
