# Generated by Django 6.0.3 on 2026-05-18 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_project_project_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_status_name', models.CharField(max_length=50)),
                ('leadstatus_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='leads',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.leadstatus'),
        ),
    ]
