# Generated by Django 6.0.3 on 2026-05-18 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_leadstatus_alter_leads_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='accounts.leads')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.leadstatus')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employeeinfo')),
            ],
        ),
    ]
