# Generated by Django 6.0.3 on 2026-05-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
