# Generated by Django 6.0.3 on 2026-05-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('leads', 'Leads'), ('projects', 'Projects'), ('reminders', 'Reminders'), ('employees', 'Employees'), ('companies', 'Companies'), ('settings', 'Settings')], max_length=50),
        ),
    ]
