# Generated by Django 6.0.3 on 2026-05-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_permission_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('leads', 'Leads'), ('projects', 'Projects'), ('reminders', 'Reminders'), ('employees', 'Employees'), ('companies', 'Companies'), ('settings', 'Settings'), ('permissions', 'Permissions')], max_length=50),
        ),
        migrations.AlterField(
            model_name='permission',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('superadmin', 'Super Admin'), ('company', 'Company'), ('employee', 'Employee')], max_length=20),
        ),
    ]
